# Generated by ariadne-codegen on 2023-11-01 10:05
# Source: graphql/orange_queries.graphql

from typing import Dict, Optional, Union

from .base_client import BaseClient
from .base_model import UNSET, UnsetType
from .input_types import PeachOrderCreateInput, PeachOrderPaymentInput
from .peach_order_create import PeachOrderCreate
from .peach_order_payment import PeachOrderPayment


def gql(q: str) -> str:
    return q


class Client(BaseClient):
    def peach_order_create(
        self, input: Union[Optional[PeachOrderCreateInput], UnsetType] = UNSET
    ) -> PeachOrderCreate:
        query = gql(
            """
            mutation peachOrderCreate($input: PeachOrderCreateInput) {
              peachOrderCreate(input: $input) {
                orderCancelHour
                orderCode
                orderId
                payableAmount
                paymentCode
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return PeachOrderCreate.model_validate(data)

    def peach_order_payment(
        self, input: Union[Optional[PeachOrderPaymentInput], UnsetType] = UNSET
    ) -> PeachOrderPayment:
        query = gql(
            """
            mutation peachOrderPayment($input: PeachOrderPaymentInput) {
              peachOrderPayment(input: $input)
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return PeachOrderPayment.model_validate(data)
