# Generated by ariadne-codegen on 2023-11-01 10:05
# Source: graphql/orange_queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class PeachOrderPayment(BaseModel):
    peach_order_payment: Optional[str] = Field(alias="peachOrderPayment")


PeachOrderPayment.model_rebuild()
