# Generated by ariadne-codegen on 2023-11-01 10:05
# Source: graphql/orange_queries.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class PeachOrderCreate(BaseModel):
    peach_order_create: Optional["PeachOrderCreatePeachOrderCreate"] = Field(
        alias="peachOrderCreate"
    )


class PeachOrderCreatePeachOrderCreate(BaseModel):
    order_cancel_hour: Optional[int] = Field(alias="orderCancelHour")
    order_code: Optional[str] = Field(alias="orderCode")
    order_id: Optional[str] = Field(alias="orderId")
    payable_amount: Optional[Any] = Field(alias="payableAmount")
    payment_code: Optional[str] = Field(alias="paymentCode")


PeachOrderCreate.model_rebuild()
PeachOrderCreatePeachOrderCreate.model_rebuild()
